name: C/C++ CI

on:
  push:
    branches: [ cleanup ]
  pull_request:
    branches: [ cleanup ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Installation Test
      run: ./install.sh
    - name: Build Test
      run: make
