name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Installation Test
      run: ./install.sh
    - name: Build Test
      run: cd src; make demo

  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Installation Test
      run: make run
