 
name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Installation
      run: make install

    - name: Build
      run: make install
