 
name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Installation
      uses: actions/checkout@v2
      run: make install;

    - name: Build
      run: make install;
