name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    push:
      branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installation Test
      run: ./install.sh

    # gfx/gl.hpp: fatal error: GL/glew.h: No such file or director
    #- name: Build Test
    #  run: make -C src demo
